parameters:
  transaction.transaction.class: Fone\TransactionBundle\Manager\TransactionManager
  transaction.transaction.entity_class: Fone\TransactionBundle\Document\Transaction

services:
  transaction.transaction_manager:
    class: "%transaction.transaction.class%"
    arguments: [ "%transaction.transaction.entity_class%" ]
    parent: core.core_manager