default:
    resource: "@CoreBundle/Controller"
    type:     annotation
    prefix:   /

main_page:
    resource: "@MainPageBundle/Controller"
    type:     annotation
    prefix:   /portal/

transaction:
    resource: "@TransactionBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /transactions/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"