services:
  core.core_manager:
    abstract: true
    class: Fone\CoreBundle\Manager\CoreManager
    calls:
      - [ setEntityProperties, [ "@doctrine_mongodb.odm.default_document_manager" ] ]
      - [ setTranslator, [ "@translator" ] ]
      - [ setSession, [ "@session" ] ]