<?php
/**
 * Created by PhpStorm.
 * User: christopher
 * Date: 17/12/16
 * Time: 0:42
 */

namespace Fone\UserBundle\Manager;

use Fone\CoreBundle\Manager\CoreManager;
use Fone\UserBundle\Document\Repository\AccountRepository;

class AccountManager extends CoreManager
{
    public function findByUser($user)
    {
        return $this->getRepository()->findByUser($user);
    }

    /** @return AccountRepository */
    protected function getRepository()
    {
        return parent::getRepository(); // TODO: Change the autogenerated stub
    }
}